name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

env:
  COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ env.COMMIT_SHA }}

      - name: Install dependencies
        run: |
          npm ci
